-- Follow-through — local authentication for the MySQL provider.
--
-- Supabase Auth is a hosted service and cannot work without internet, so an offline installation
-- needs its own identity store. This is that store: credentials and sessions, nothing else.
--
-- Design decisions that matter:
--
--   * Password hashes are produced by Node's scrypt and stored encoded. MySQL has no scrypt, so the
--     routines here store and return the encoded hash and Node verifies it in constant time. The
--     database never sees a plaintext password.
--   * Sessions are stored as the SHA-256 of a 256-bit random token, so a dump of this table yields no
--     usable session. Revocation is a row update, so a revoked session stops working immediately —
--     the property Supabase provided with global sign-out.
--   * Reads are FUNCTIONS and writes are PROCEDURES with a single-statement body. MySQL forbids table
--     modification inside a stored function, and a BEGIN…END body would need a DELIMITER directive
--     that the Node driver does not understand. Keeping every body to one statement avoids both.
--   * The application user has no SELECT on any base table, so cb_local_credential is the only route
--     to a password hash, and it returns only the row for a supplied email.

-- ---------------------------------------------------------------- tables

create table if not exists cb_local_credentials (
  user_id char(36) not null,
  password_hash varchar(255) not null,
  algo varchar(24) not null default 'scrypt',
  failed_attempts int not null default 0,
  locked_until datetime(3) null,
  updated_at datetime(3) not null default (utc_timestamp(3)),
  primary key (user_id),
  constraint cb_local_credentials_account foreign key (user_id) references cb_accounts(id)
) engine=InnoDB;

create table if not exists cb_local_sessions (
  id char(36) not null,
  user_id char(36) not null,
  token_hash char(64) not null,
  issued_at datetime(3) not null default (utc_timestamp(3)),
  expires_at datetime(3) not null,
  revoked_at datetime(3) null,
  user_agent varchar(200) not null default '',
  primary key (id),
  unique key cb_local_sessions_token (token_hash),
  key cb_local_sessions_user (user_id, revoked_at, expires_at),
  constraint cb_local_sessions_account foreign key (user_id) references cb_accounts(id)
) engine=InnoDB;

-- ---------------------------------------------------------------- reads

-- The credential row for an email, or null. The only route to a password hash.
drop function if exists cb_local_credential;
create function cb_local_credential(p_email varchar(320)) returns json
  reads sql data
  return (
    select json_object(
      'user_id',       a.id,
      'email',         a.email,
      'password_hash', c.password_hash,
      'algo',          c.algo,
      'locked_until',  date_format(c.locked_until, '%Y-%m-%dT%H:%i:%s.%fZ'),
      'confirmed',     cast(a.email_confirmed_at is not null as json)
    )
    from cb_accounts a
    join cb_local_credentials c on c.user_id = a.id
    where lower(a.email) = lower(trim(p_email))
    limit 1
  );

-- Resolves a session token hash to its account, or null if unknown, revoked or expired.
drop function if exists cb_local_session_lookup;
create function cb_local_session_lookup(p_token_hash char(64)) returns json
  reads sql data
  return (
    select json_object(
      'user_id', s.user_id,
      'email',   a.email,
      'session', s.id
    )
    from cb_local_sessions s
    join cb_accounts a on a.id = s.user_id
    where s.token_hash = p_token_hash
      and s.revoked_at is null
      and s.expires_at > utc_timestamp(3)
    limit 1
  );

-- ---------------------------------------------------------------- writes
-- Each body is a single statement. The caller supplies the session id, so nothing needs to be returned.

-- Creates a session. The id and the token hash are generated by the caller; only the hash is stored.
drop procedure if exists cb_local_session_create;
create procedure cb_local_session_create(
  in p_id char(36), in p_user_id char(36), in p_token_hash char(64),
  in p_ttl_hours int, in p_user_agent varchar(200))
  insert into cb_local_sessions (id, user_id, token_hash, expires_at, user_agent)
  values (p_id, p_user_id, p_token_hash, utc_timestamp(3) + interval p_ttl_hours hour, p_user_agent);

-- Revokes one session by its token hash.
drop procedure if exists cb_local_session_revoke;
create procedure cb_local_session_revoke(in p_token_hash char(64))
  update cb_local_sessions set revoked_at = utc_timestamp(3)
   where token_hash = p_token_hash and revoked_at is null;

-- Revokes every live session for an account. Sign-out everywhere.
drop procedure if exists cb_local_session_revoke_all;
create procedure cb_local_session_revoke_all(in p_user_id char(36))
  update cb_local_sessions set revoked_at = utc_timestamp(3)
   where user_id = p_user_id and revoked_at is null;

-- Records a failed sign-in, locking the account for 15 minutes on the fifth.
drop procedure if exists cb_local_login_failed;
create procedure cb_local_login_failed(in p_user_id char(36))
  update cb_local_credentials
     set failed_attempts = failed_attempts + 1,
         locked_until = case
           when failed_attempts + 1 >= 5 then utc_timestamp(3) + interval 15 minute
           else locked_until
         end
   where user_id = p_user_id;

-- Clears the failure counter and any lock after a successful sign-in.
drop procedure if exists cb_local_login_ok;
create procedure cb_local_login_ok(in p_user_id char(36))
  update cb_local_credentials
     set failed_attempts = 0, locked_until = null
   where user_id = p_user_id;

-- Sets or replaces an account's password hash. Used by the operator seeding script.
drop procedure if exists cb_local_credential_set;
create procedure cb_local_credential_set(in p_user_id char(36), in p_hash varchar(255), in p_algo varchar(24))
  insert into cb_local_credentials (user_id, password_hash, algo)
  values (p_user_id, p_hash, p_algo)
  on duplicate key update password_hash = p_hash, algo = p_algo,
                          failed_attempts = 0, locked_until = null,
                          updated_at = utc_timestamp(3);

-- Removes any credentials that no longer have an account, and any session that has expired more than
-- a week ago. Housekeeping the operator can schedule.
drop procedure if exists cb_local_purge;
create procedure cb_local_purge(in p_days int)
  delete from cb_local_sessions where expires_at < utc_timestamp(3) - interval p_days day;
